/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CaffeineEntry = IDL.Record({
  'id' : IDL.Nat,
  'amountMg' : IDL.Nat,
  'consumptionTime' : IDL.Nat,
  'drinkName' : IDL.Text,
});
export const CaffeinePreset = IDL.Record({
  'id' : IDL.Nat,
  'defaultAmountMg' : IDL.Nat,
  'drinkName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserSettings = IDL.Record({ 'dailyLimitMg' : IDL.Nat });
export const UserData = IDL.Record({
  'presets' : IDL.Vec(CaffeinePreset),
  'entries' : IDL.Vec(CaffeineEntry),
  'settings' : UserSettings,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCaffeineEntry' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [CaffeineEntry],
      [],
    ),
  'addCaffeinePreset' : IDL.Func([IDL.Text, IDL.Nat], [CaffeinePreset], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCaffeineEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserData' : IDL.Func([], [UserData], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CaffeineEntry = IDL.Record({
    'id' : IDL.Nat,
    'amountMg' : IDL.Nat,
    'consumptionTime' : IDL.Nat,
    'drinkName' : IDL.Text,
  });
  const CaffeinePreset = IDL.Record({
    'id' : IDL.Nat,
    'defaultAmountMg' : IDL.Nat,
    'drinkName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserSettings = IDL.Record({ 'dailyLimitMg' : IDL.Nat });
  const UserData = IDL.Record({
    'presets' : IDL.Vec(CaffeinePreset),
    'entries' : IDL.Vec(CaffeineEntry),
    'settings' : UserSettings,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCaffeineEntry' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [CaffeineEntry],
        [],
      ),
    'addCaffeinePreset' : IDL.Func([IDL.Text, IDL.Nat], [CaffeinePreset], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCaffeineEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserData' : IDL.Func([], [UserData], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };